### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by chadhietala** [chadhietala/ember-cli-builder#19]
Correctly it's confusing that ember-cli has a "builder" model and this would introduce another builder object.  It also doesn't correctly describe what this does. Simply put this gathers up all of the source and transpiles/compiles it. It also leaves behind an artifact that is used by a linker to be used to resolve the final output.  This sounds like a compiler, despite the fact it actually may have N transpilers/compilers.  Perhaps it should be renamed to `ember-cli-compiler`. Thoughts?

**Comment by stefanpenner** [comment]
builder isn't bad, maybe assembler? Compiler may be confused with the transpile (true compile) steps.

**Comment by chadhietala** [comment]
Yea was thinking assembler.
